directoryserver_db_image:
  build: ./directoryServer/target/docker/database
  expose:
   - 3306
  container_name: directory-db

directoryserver_app_image:
  image: ccctechcenter/cccnext-directory-server:${IMAGE_TAG}
  volumes:
     - ./directoryServer/target:/opt/edexchange
  ports:
   - 8080:8080
   - 8443:8443
  environment:
   - SPRING_PROFILES_ACTIVE=${profile}
   - DB_SERVER=directory-db
   - MAIL_SMTP_HOST=${MAIL_SMTP_HOST}
   - MAIL_SMTP_USERNAME=${MAIL_SMTP_USERNAME}
   - MAIL_SMTP_PASSWORD=${MAIL_SMTP_PASSWORD}
  links:
   - directoryserver_db_image
  container_name: directory-app

network-server:
  labels:
    io.rancher.scheduler.affinity:host_label: service-name=network-server
    io.rancher.container.pull_image: always
  image: ccctechcenter/cccnext-network-server:${IMAGE_TAG}
  volumes:
     - ./networkServer/target:/opt/edexchange
  ports:
   - 8081:9000
   - 443:9443
  environment:
   - SPRING_PROFILES_ACTIVE=${profile}
   - DB_SERVER=${NETWORK_DB_HOST}
   - DIRECTORY_SERVER=directory-server
   - DIRECTORY_SERVER_PORT=8080
  extra_hosts:
   - networkserver_db_image:${NETWORK_DB_HOST}
   - directoryserver_app_image:${DIRECTORY_HOST}
   - directory-server:${DIRECTORY_HOST}
