directoryserver_app_image:
  image: edex/directory-server
  volumes:
     - ./directoryServer/target:/opt/edexchange
  ports:
   - 8080:8080
  environment:
   - SPRING_PROFILES_ACTIVE=${profile}
   - DB_SERVER=${DIRECTORY_DB_HOST}
  container_name: directory-app
