db_image:
  build: ./target/docker/database
  expose:
   - "3306"
  container_name: network-db
app_image:
  build: ./target/docker
  volumes:
     - ./target:/opt/edexchange
  ports:
   - "9000:9000"
   - "9449:9443"
  links:
   - db_image
  environment:
   - SPRING_PROFILES_ACTIVE=qa
  container_name: network-app